version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8888:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - '27017:27017'
volumes:
  mongodb_data:
  mongodb_config:
